version: 2.1
commands:
  restore_cache_cmd:
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "web/package-lock.json" }}
            - vi-dependencies-
  save_cache_cmd:
    steps:
      - save_cache:
          paths:
            - ./web/node_modules
          key: v1-dependencies-{{ checksum "web/package-lock.json" }}

executors:
  docker-publisher:
    working_directory: ~/hailtechno # directory where steps will run
    environment:
      IMAGE_NAME: hailtechno/hailtechno-web
    docker:
      - image: circleci/buildpack-deps:stretch

jobs:
  build-and-test:
    working_directory: ~/hailtechno
    docker:
      - image: circleci/node:12.16.1
    steps:
      - checkout
      - run: |
          - cd web
          - npm install
          - NODE_ENV npm run build:dev
      - save_cache_cmd
      - run: |
          - pwd
          - ls
      #- run: echo "Test Me"
      - persist_to_workspace:
          root: ~/hailtechno
          paths:
            - dist
      - run: ls

  docker-build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          name: Build latest Docker image
          command: docker build . -t $IMAGE_NAME:latest
      # - run:
      #     name: Build tagged Docker iamge
      #     command: docker built . -t $IMAGE_NAME:${CIRCLE_TAG}
      - run:
          name: Archive Docker Image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: ~/hailtechno
          paths:
            - ./image.tar

  docker-publish:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i image.tar
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin
            docker push $IMAGE_NAME:latest
            # docker push $IMAGE_NAME:${CIRCLE_TAG}

# Workflow Filters
wf-filters:
  only-main: &only-main
    branches:
      only: main
  only-main-and-tags: &only-main-and-tags
    branches:
      only: main
    tags:
      only: /^\d+\.\d+\.\d+$/

# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  version: 2.1
  # Require manual action on branches for docker deploy
  CI-Branch:
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build-and-test

  # Run automatically on main
  CI-Main:
    jobs:
      - build-and-test:
          filters: *only-main
      - docker-build:
          context: hailtechno
          requires:
            - build-and-test
          filters: *only-main-and-tags
      - docker-publish:
          context: hailtechno
          requires:
            - docker-build
          filters: *only-main-and-tags
