---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "hailtechno-web-service"
  labels:
    app: "hailtechno-web"
spec:
  ports:
  - name: http
    protocol: "TCP"
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
  selector:
    app: "hailtechno-web"
  type: "LoadBalancer"