apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hailtechno-web
  name: hailtechno-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hailtechno-web
  template:
    metadata:
      labels:
        app: hailtechno-web
    spec:
      containers:
      - env:
          # These are set in the CI when I do webpack:build
#        - name: HAILTECHNO_HOST
#          value: https://hailtechno-svc.hailtechno.com
#        - name: HAILTECHNO_PORT
#          value: "3000"
        image: hailtechno/hailtechno-web:latest
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 30
        name: hailtechno-web
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred
